name: Bump Version

# on:
#   pull_request:
#     types: [closed]
#     branches: [main]

on:
  pull_request:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    # if: |
    #   github.event.pull_request.merged
    #   && (
    #       contains(github.event.pull_request.labels.*.name, 'bump patch')
    #       || contains(github.event.pull_request.labels.*.name, 'bump minor')
    #       || contains(github.event.pull_request.labels.*.name, 'bump major')
    #   )

    if: |
      (
        contains(github.event.pull_request.labels.*.name, 'bump patch')
        || contains(github.event.pull_request.labels.*.name, 'bump minor')
        || contains(github.event.pull_request.labels.*.name, 'bump major')
      )

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Bump
        env:
          BUMP_PATCH_PRESENT: ${{ contains(github.event.pull_request.labels.*.name, 'bump patch') }}
          BUMP_MINOR_PRESENT: ${{ contains(github.event.pull_request.labels.*.name, 'bump minor') }}
          BUMP_MAJOR_PRESENT: ${{ contains(github.event.pull_request.labels.*.name, 'bump major') }}
          PR_BODY: $github.event.pull_request.body
        run: |
          echo: $PR_BODY

          name=$($PR_BODY | grep -o -P "(?<=# VERSION NAME).*(?---)")
          echo $name

          description=$($PR_BODY | grep -o -P "(?<=# DESCRIPTION NAME).*(?---)")
          echo $description

          if [[ $BUMP_PATCH_PRESENT == 'true' ]]; then
              node createVersion.js patch $name $description
          fi
          if [[ $BUMP_MINOR_PRESENT == 'true' ]]; then
              node createVersion.js minor $name $description
          fi
          if [[ $BUMP_MAJOR_PRESENT == 'true' ]]; then
              node createVersion.js major $name $description
          fi
